---
- name: Wipe the app
  tags: wipe
  when: web_app_full_wipe
  block:
    - name: Stop docker-compose
      community.docker.docker_compose:
        project_src: "{{ base_path }}"
        state: absent
        remove_volumes: true

    - name: Delete folder
      file:
        path: "{{ base_path }}"
        state: absent