version: '3'

x-logging: &logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}"

services:

  app_python:
    image: draeston/devops_app:latest
    ports:
      - "8080:3000"
    networks:
      - app_python
      - loki
    logging: *logging

  loki:
    image: grafana/loki:2.6.1
    expose:
      - 3100
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    logging: *logging

  promtail:
    image: grafana/promtail:2.6.1
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - app_python
      - loki
    logging: *logging

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./loki.yml:/etc/grafana/provisioning/datasources/datasource.yml
    ports:
      - "3000:3000"
    networks:
      - loki
    logging: *logging

networks:
  app_python:
  loki: